name: Liquibase_Docker_GitHub-Hosted

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v2
  
    - name: RunLiquibaseCLICommands
  
      run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.2.0/liquibase-4.2.0.zip --output liquibase-4.2.0.zip
          unzip -o -d liquibase liquibase-4.2.0.zip
          node --version
          liquibase --version
          node NodeJS/liquibase_dev"${{ github.event.inputs.environment }}".js
    
    
      
    - name: docker
      run: export DOCKER_HOST=tcp://127.0.0.1:5432
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args:  --url="jdbc:postgresql://localhost:5432/test?currentSchema=public" --changeLogFile=./src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 status --verbose
     
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args:  --add -network="host" --url="jdbc:postgresql://host.docker.internal:5432/test?currentSchema=public" --changeLogFile=./src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 --logLevel=debug update
 
