name: Liquibase_Docker_GitHub-Hosted

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v2
    - name: docker
      run: docker run --add-host=host.docker.internal:127.0.0.1
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args:  --url="jdbc:postgresql://host.docker.internal:5432/test?currentSchema=public" --changeLogFile=./src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 status --verbose
     
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args:  --url="jdbc:postgresql://host.docker.internal:5432/test?currentSchema=public" --changeLogFile=./src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 --logLevel=debug update
 
