name: Liquibase_Docker

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDocker:
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v2
    - name: docker
      run: docker run --network host //liquibase/liquibase:latest
    - uses: docker://liquibase/liquibase:latest
      with:
        args:  --url="jdbc:postgresql://127.0.0.1:5432/test?currentSchema=public" --changeLogFile=./src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 --logLevel=debug update
        
       
