name: Liquibase_Docker

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDocker:
    runs-on: ubuntu-latest
 
    steps: 
    - uses: actions/checkout@v2
    
    - uses: docker://liquibase/liquibase:latest
    - name: jkkk
      run: docker run --rm --net="host" --url="jdbc:postgresql://host.docker.internal:5432/test?currentSchema=public" --changeLogFile=/src/main/resources/changelogs/changelog.postgree.sql --username=postgres --password=Kirilova%618249 status --verbose
