name: Liquibase Migrations

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
         
        - uses: actions/checkout@v2
        - uses: liquibase-github-actions/update@v4.24.0
          with:
                  
            classpath: "src/main/resources/changelogs/"
            changeLogFile: "changelog.postgree.sql"
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            #driver: liquibase.ext.hibernate.database.connection.HibernateDriver
            url: "jdbc:postgresql://localhost:49254/test"
        - uses: liquibase-github-actions/generate-changelog@v4.24.0
          with:
            url: jdbc:postgresql://${{env.POSTGRES_HOST}}:${{env.POSTGRES_PORT}}/${{env. DB_NAME}}
            headless: true          
            logLevel: INFO
            
            
