name: Liquibase Migrations

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER:  ${{ secrets.USERNAME}}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD}}
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    
    steps:
         
        - uses: actions/checkout@v2
        - uses: liquibase-github-actions/update@v4.24.0
          with:
                  
            classpath: "src/main/resources/changelogs/"
            changeLogFile: "changelog.postgree.sql"
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            url: "jdbc:postgresql://postgres:5432/test"
        - uses: liquibase-github-actions/generate-changelog@v4.24.0
          with:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            url: "jdbc:postgresql://postgres:5432/test"
            headless: true          
            logLevel: INFO
            
            
